### ISSUE TITLE
entering any text in the dialog ends with an error

### ISSUE THREAD

**Issue by bossrus** [mrvlasyuk/tiny_code_improver#1]
...\html_test>improve_code
2023-07-18 15:14:29.762 | INFO     | tinycodeimprover.code_improver:main:107 - Starting CodeImprover
2023-07-18 15:14:29.766 | INFO     | tinycodeimprover.code_improver:__init__:11 - Initializing CodeImprover for ...\html_test\code_improver.yaml
2023-07-18 15:14:29.920 | INFO     | tinycodeimprover.code_improver:log_initial_context:56 - 
Prefix: Project contains following files: ['index.css', 'index.html']
### Content of 'index.css' file:

body {
    margin: 0;
    padding: 0;
    display: flex;
    justify-content: center;
    font-family: "Inter", sans-serif;
}

.container {
    max-width: 1024px;
    display: flex;
    justify-content: space-between;
    align-items: center;
    flex-direction: column;
}

.sub_container{
    width: 100%;
    padding: 0 60px;
    box-sizing: border-box;
}

.sub_container_bottom{
    width: 100%;
    p
...
Files: ['index.css', 'index.html']
Number of tokens = 4166

2023-07-18 15:14:29.921 | INFO     | tinycodeimprover.code_improver:start_interactive_dialog:75 - Starting interactive dialog. Type 'exit' to end the conversation.

User: what are you doing?
2023-07-18 15:15:04.819 | INFO     | tinycodeimprover.code_improver:fix_prompt:71 -
Prompt: what are you doing?
used_tokens = 4201, tokens_left = 3799
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Scripts\improve_code.exe\__main__.py", line 7, in <module>
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\tinycodeimprover\code_improver.py", line 116, in main
    code_improver.start_interactive_dialog()
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\tinycodeimprover\code_improver.py", line 103, in start_interactive_dialog
    last_output = self.generate_reply(prompt)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\tinycodeimprover\code_improver.py", line 59, in generate_reply
    return self.gpt.display_reply_sync(prompt)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\tinycodeimprover\chatgpt.py", line 68, in display_reply_sync
    return asyncio.run(self.display_reply(prompt))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\tinycodeimprover\chatgpt.py", line 62, in display_reply
    async for new_text in self.generate_reply(prompt):
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\tinycodeimprover\chatgpt.py", line 29, in generate_reply
    async for new_text in stream:
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\tinycodeimprover\utils.py", line 67, in get_gpt_reply_stream
    stream = await openai.ChatCompletion.acreate(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\chat_completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 217, in acreate
    response, _, api_key = await requestor.arequest(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 382, in arequest
    resp, got_stream = await self._interpret_async_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 726, in _interpret_async_response
    self._interpret_response_line(
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: The model: `gpt-4` does not exist

**Comment by mrvlasyuk** [comment]
` The model: gpt-4 does not exist` - You should have access to gpt-4 model.
